use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::time::{SystemTime, UNIX_EPOCH};

#[test]
fn rebuild_index_handles_empty_task_set() {
    let repo = setup_repo("cli-rebuild-empty");

    let output = run_vdoc(repo.path(), ["rebuild", "index"]);

    assert_success(&output);
    let index = fs::read_to_string(repo.path().join("docs/tasks/index.md")).unwrap();
    assert!(index.contains("This index is generated by `vdoc rebuild index`."));
    assert!(index.contains("## Doing\n\nNo tasks.\n\n## Planned"));
    assert!(index.contains("## Planned\n\nNo tasks.\n\n## Blocked"));
    assert!(index.contains("## Blocked\n\nNo tasks.\n\n## Done"));
    assert!(index.ends_with("## Done\n\nNo tasks.\n\n"));
}

#[test]
fn rebuild_index_groups_active_blocked_and_done_tasks() {
    let repo = setup_repo("cli-rebuild-groups");
    repo.write(
        "docs/tasks/active/2-doing-task.md",
        &task_markdown(2, "Doing Task", "doing"),
    );
    repo.write(
        "docs/tasks/active/3-planned-task.md",
        &task_markdown(3, "Planned Task", "planned"),
    );
    repo.write(
        "docs/tasks/active/4-blocked-task.md",
        &task_markdown(4, "Blocked Task", "blocked"),
    );
    repo.write(
        "docs/tasks/done/5-done-task.md",
        &task_markdown(5, "Done Task", "done"),
    );

    let output = run_vdoc(repo.path(), ["rebuild", "index"]);

    assert_success(&output);
    let index = fs::read_to_string(repo.path().join("docs/tasks/index.md")).unwrap();
    assert_ordered(
        &index,
        &[
            "## Doing\n\n- 2 Doing Task",
            "## Planned\n\n- 3 Planned Task",
            "## Blocked\n\n- 4 Blocked Task",
            "## Done\n\n- 5 Done Task",
        ],
    );
}

#[test]
fn rebuild_index_preserves_task_index_frontmatter() {
    let repo = setup_repo("cli-rebuild-frontmatter");
    repo.write(
        "docs/tasks/index.md",
        "---\nid: 1\ntitle: Task Index\nkind: task-index\ntags:\n  - custom\n---\n\nstale\n",
    );

    let output = run_vdoc(repo.path(), ["rebuild", "index"]);

    assert_success(&output);
    let index = fs::read_to_string(repo.path().join("docs/tasks/index.md")).unwrap();
    assert!(index
        .starts_with("---\nid: 1\ntitle: Task Index\nkind: task-index\ntags:\n  - custom\n---\n"));
}

#[test]
fn rebuild_index_dry_run_prints_proposed_output_without_writing() {
    let repo = setup_repo("cli-rebuild-dry-run");
    let before = fs::read_to_string(repo.path().join("docs/tasks/index.md")).unwrap();

    let output = run_vdoc(repo.path(), ["rebuild", "index", "--dry-run"]);

    assert_success(&output);
    assert!(stdout(&output).contains("vdoc rebuild index dry-run:\n---\n"));
    assert!(stdout(&output).contains("This index is generated by `vdoc rebuild index`."));
    let after = fs::read_to_string(repo.path().join("docs/tasks/index.md")).unwrap();
    assert_eq!(after, before);
}

#[test]
fn rebuild_index_json_output_is_stable() {
    let repo = setup_repo("cli-rebuild-json");

    let output = run_vdoc(repo.path(), ["rebuild", "index", "--dry-run", "--json"]);

    assert_success(&output);
    let value: Value = serde_json::from_str(&stdout(&output)).unwrap();
    assert_eq!(value["command"], "rebuild index");
    assert_eq!(value["dry_run"], true);
    assert_eq!(value["path"], "docs/tasks/index.md");
    assert_eq!(value["action"], "overwrite");
    assert!(value["content"]
        .as_str()
        .unwrap()
        .contains("This index is generated by `vdoc rebuild index`."));
}

#[test]
fn rebuild_index_twice_produces_no_diff() {
    let repo = setup_repo("cli-rebuild-stable");

    assert_success(&run_vdoc(repo.path(), ["rebuild", "index"]));
    let first = fs::read_to_string(repo.path().join("docs/tasks/index.md")).unwrap();
    let output = run_vdoc(repo.path(), ["rebuild", "index", "--json"]);

    assert_success(&output);
    let second = fs::read_to_string(repo.path().join("docs/tasks/index.md")).unwrap();
    let value: Value = serde_json::from_str(&stdout(&output)).unwrap();
    assert_eq!(second, first);
    assert_eq!(value["action"], "keep");
}

fn setup_repo(name: &str) -> TestRepo {
    let repo = TestRepo::new(name);
    assert_success(&run_vdoc(repo.path(), ["init"]));
    repo
}

fn task_markdown(id: u64, title: &str, status: &str) -> String {
    format!(
        "---\nid: {id}\ntitle: {title}\nkind: task\ntype: feature\nstatus: {status}\nadrs: []\ndepends_on: []\n---\n\n# {title}\n"
    )
}

fn assert_ordered(haystack: &str, needles: &[&str]) {
    let mut cursor = 0;
    for needle in needles {
        let offset = haystack[cursor..]
            .find(needle)
            .unwrap_or_else(|| panic!("missing ordered text: {needle}"));
        cursor += offset + needle.len();
    }
}

fn run_vdoc<const N: usize>(cwd: &Path, args: [&str; N]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_vdoc"))
        .current_dir(cwd)
        .args(args)
        .output()
        .unwrap()
}

fn assert_success(output: &Output) {
    assert!(
        output.status.success(),
        "expected success\nstdout:\n{}\nstderr:\n{}",
        stdout(output),
        stderr(output)
    );
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

struct TestRepo {
    root: PathBuf,
}

impl TestRepo {
    fn new(name: &str) -> Self {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!("vibe-doc-{name}-{unique}"));
        fs::create_dir_all(&root).unwrap();
        Self { root }
    }

    fn path(&self) -> &Path {
        &self.root
    }

    fn write(&self, path: &str, content: &str) {
        let full_path = self.root.join(path);
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(full_path, content).unwrap();
    }
}

impl Drop for TestRepo {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}
